from __future__ import annotations

from app.config import Settings
from app.domain.rwa import AssetTemplate, AssetType, HashKeyChainConfig

HASHKEY_DOCS_BASE = "https://docs.hashkeychain.net"
HASHKEY_NETWORK_INFO_URL = (
    f"{HASHKEY_DOCS_BASE}/docs/Build-on-HashKey-Chain/network-info"
)
HASHKEY_TOKEN_CONTRACTS_URL = (
    f"{HASHKEY_DOCS_BASE}/docs/Build-on-HashKey-Chain/Token-Contracts"
)
HASHKEY_KYC_URL = f"{HASHKEY_DOCS_BASE}/docs/Build-on-HashKey-Chain/Tools/KYC"
HASHKEY_SUBGRAPH_URL = (
    f"{HASHKEY_DOCS_BASE}/docs/Build-on-HashKey-Chain/Tools/Subgraph"
)
HASHKEY_ABOUT_URL = f"{HASHKEY_DOCS_BASE}/docs/About-HashKey-Chain"
HASHKEY_CPIC_MMF_URL = (
    "https://www.prnewswire.com/news-releases/"
    "cpic-estable-mmf-launches-on-hashkey-chain-with-100m-first-day-subscriptions-302408505.html"
)
HASHKEY_SILVER_RWA_URL = (
    "https://group.hashkey.com/en/newsroom/"
    "hashkey-chain-supports-the-onchain-issuance-of-hk-s-first-regulated-silverbacked-rwa-token"
)


def build_chain_config(settings: Settings) -> HashKeyChainConfig:
    return HashKeyChainConfig(
        default_execution_network="mainnet",
        testnet_chain_id=settings.hashkey_testnet_chain_id,
        testnet_rpc_url=settings.hashkey_testnet_rpc_url,
        testnet_explorer_url=settings.hashkey_testnet_explorer_url,
        mainnet_chain_id=settings.hashkey_mainnet_chain_id,
        mainnet_rpc_url=settings.hashkey_mainnet_rpc_url,
        mainnet_explorer_url=settings.hashkey_mainnet_explorer_url,
        plan_registry_address=settings.plan_registry_address or "",
        kyc_sbt_address=settings.kyc_sbt_address or "",
        docs_urls=[
            HASHKEY_ABOUT_URL,
            HASHKEY_NETWORK_INFO_URL,
            HASHKEY_TOKEN_CONTRACTS_URL,
            HASHKEY_KYC_URL,
            HASHKEY_SUBGRAPH_URL,
        ],
    )


def build_asset_library(chain_config: HashKeyChainConfig) -> list[AssetTemplate]:
    chain_id = chain_config.mainnet_chain_id
    return [
        AssetTemplate(
            asset_id="hsk-usdt",
            symbol="USDT",
            name="HashKey USDT",
            asset_type=AssetType.STABLECOIN,
            description="HashKey Chain 官方列出的主网 USDT 合约，适合作为稳定币收益与流动性基准。",
            issuer="Tether / bridge representation",
            custody="Bridge-backed ERC20 on HashKey Chain",
            chain_id=chain_id,
            contract_address="0xf1b50ed67a9e2cc94ad3c477779e2d4cbfff9029",
            settlement_asset="USDT",
            execution_style="erc20",
            benchmark_apy=0.055,
            expected_return_low=0.032,
            expected_return_base=0.052,
            expected_return_high=0.068,
            price_volatility=0.015,
            max_drawdown_180d=0.02,
            avg_daily_volume_usd=4_600_000,
            redemption_days=0,
            lockup_days=0,
            management_fee_bps=35,
            entry_fee_bps=0,
            exit_fee_bps=0,
            slippage_bps=6,
            depeg_events_90d=1,
            worst_depeg_bps_90d=38,
            issuer_disclosure_score=0.7,
            custody_disclosure_score=0.68,
            audit_disclosure_score=0.62,
            contract_is_upgradeable=True,
            has_admin_key=True,
            oracle_count=2,
            oracle_sources=["HashKey Oracle / APRO", "secondary market"],
            requires_kyc_level=0,
            minimum_ticket_usd=100,
            tags=["stablecoin", "liquidity", "yield-base"],
            thesis="适合作为流动性底仓和低波动收益腿，但需要显式看待脱锚与赎回信心风险。",
            fit_summary="更适合保守或均衡型配置，重点承担现金管理和出入金缓冲角色。",
            evidence_urls=[HASHKEY_TOKEN_CONTRACTS_URL, HASHKEY_NETWORK_INFO_URL],
            featured=True,
        ),
        AssetTemplate(
            asset_id="hsk-usdc",
            symbol="USDC",
            name="HashKey USDC",
            asset_type=AssetType.STABLECOIN,
            description="HashKey Chain 官方列出的主网 Bridged USDC，可作为稳定币与 MMF 的比较基准。",
            issuer="Circle / bridged deployment",
            custody="Bridged USDC on HashKey Chain",
            chain_id=chain_id,
            contract_address="0x054ed45810DbBAb8B27668922D110669c9D88D0a",
            settlement_asset="USDC",
            execution_style="erc20",
            benchmark_apy=0.052,
            expected_return_low=0.03,
            expected_return_base=0.049,
            expected_return_high=0.064,
            price_volatility=0.012,
            max_drawdown_180d=0.018,
            avg_daily_volume_usd=3_800_000,
            redemption_days=0,
            lockup_days=0,
            management_fee_bps=28,
            entry_fee_bps=0,
            exit_fee_bps=0,
            slippage_bps=5,
            depeg_events_90d=1,
            worst_depeg_bps_90d=26,
            issuer_disclosure_score=0.78,
            custody_disclosure_score=0.76,
            audit_disclosure_score=0.75,
            contract_is_upgradeable=False,
            has_admin_key=False,
            oracle_count=2,
            oracle_sources=["HashKey Oracle / APRO", "secondary market"],
            requires_kyc_level=0,
            minimum_ticket_usd=100,
            tags=["stablecoin", "liquidity", "benchmark"],
            thesis="在披露质量和二级流动性上通常优于一般桥接资产，适合做高流动性配置基线。",
            fit_summary="适合看重 T+0 可退出和低回撤的人群。",
            evidence_urls=[HASHKEY_TOKEN_CONTRACTS_URL, HASHKEY_NETWORK_INFO_URL],
            featured=True,
        ),
        AssetTemplate(
            asset_id="cpic-estable-mmf",
            symbol="MMF",
            name="CPIC Estable MMF",
            asset_type=AssetType.MMF,
            description="HashKey Chain 生态中披露的 tokenized USD MMF 示例，用于短久期高质量货币市场工具配置演示。",
            issuer="CPIC Investment Management / Estable",
            custody="Issuer-managed RWA custody and transfer agent stack",
            chain_id=chain_id,
            contract_address="",
            settlement_asset="USDT",
            execution_style="issuer_portal",
            benchmark_apy=0.048,
            expected_return_low=0.035,
            expected_return_base=0.046,
            expected_return_high=0.055,
            price_volatility=0.025,
            max_drawdown_180d=0.03,
            avg_daily_volume_usd=1_250_000,
            redemption_days=2,
            lockup_days=0,
            management_fee_bps=70,
            entry_fee_bps=10,
            exit_fee_bps=15,
            slippage_bps=0,
            issuer_disclosure_score=0.82,
            custody_disclosure_score=0.8,
            audit_disclosure_score=0.72,
            contract_is_upgradeable=False,
            has_admin_key=False,
            oracle_count=1,
            oracle_sources=["NAV / issuer disclosure"],
            requires_kyc_level=2,
            minimum_ticket_usd=10_000,
            tags=["rwa", "mmf", "professional-investor"],
            thesis="适合作为高流动性与收益平衡型配置，但对申赎节奏、KYC 与发行人执行依赖更强。",
            fit_summary="更适合中低风险偏好、可接受 T+2 资金周转的人群。",
            evidence_urls=[HASHKEY_CPIC_MMF_URL, HASHKEY_KYC_URL],
            featured=True,
        ),
        AssetTemplate(
            asset_id="hk-regulated-silver",
            symbol="SILV",
            name="Hong Kong Regulated Silver RWA",
            asset_type=AssetType.PRECIOUS_METAL,
            description="基于香港受监管白银 RWA 的演示模板，强调 1:1 实物映射、第三方金库托管与专业投资者门槛。",
            issuer="HashKey Chain ecosystem issuer",
            custody="Third-party vault custody for .9999 silver",
            chain_id=chain_id,
            contract_address="",
            settlement_asset="USDT",
            execution_style="issuer_portal",
            benchmark_apy=0.022,
            expected_return_low=-0.08,
            expected_return_base=0.065,
            expected_return_high=0.18,
            price_volatility=0.24,
            max_drawdown_180d=0.19,
            avg_daily_volume_usd=420_000,
            redemption_days=3,
            lockup_days=0,
            management_fee_bps=85,
            entry_fee_bps=20,
            exit_fee_bps=25,
            slippage_bps=30,
            issuer_disclosure_score=0.74,
            custody_disclosure_score=0.88,
            audit_disclosure_score=0.7,
            contract_is_upgradeable=False,
            has_admin_key=False,
            oracle_count=1,
            oracle_sources=["spot silver / issuer valuation"],
            requires_kyc_level=2,
            minimum_ticket_usd=5_000,
            tags=["rwa", "precious-metal", "inflation-hedge"],
            thesis="适合作为通胀对冲和分散化腿，但收益分布更宽、流动性与托管条款必须单独审视。",
            fit_summary="更适合均衡到进取型配置，用于补充与稳定币/MMF 不同的风险收益来源。",
            evidence_urls=[HASHKEY_SILVER_RWA_URL, HASHKEY_KYC_URL],
            featured=True,
        ),
        AssetTemplate(
            asset_id="tokenized-real-estate-demo",
            symbol="RE-1",
            name="Tokenized Real Estate Demo",
            asset_type=AssetType.REAL_ESTATE,
            description="用于 Hackathon 演示的房地产类 RWA 模板，突出申赎摩擦、分红收益与低流动性的组合特征。",
            issuer="Demo SPV",
            custody="Offchain SPV / trustee structure",
            chain_id=chain_id,
            contract_address="",
            settlement_asset="USDT",
            execution_style="issuer_portal",
            benchmark_apy=0.078,
            expected_return_low=-0.05,
            expected_return_base=0.082,
            expected_return_high=0.14,
            price_volatility=0.18,
            max_drawdown_180d=0.15,
            avg_daily_volume_usd=160_000,
            redemption_days=7,
            lockup_days=30,
            management_fee_bps=110,
            entry_fee_bps=35,
            exit_fee_bps=35,
            slippage_bps=45,
            issuer_disclosure_score=0.58,
            custody_disclosure_score=0.62,
            audit_disclosure_score=0.55,
            contract_is_upgradeable=True,
            has_admin_key=True,
            oracle_count=1,
            oracle_sources=["issuer NAV"],
            requires_kyc_level=2,
            minimum_ticket_usd=25_000,
            tags=["rwa", "real-estate", "yield"],
            thesis="收益看起来吸引人，但退出时间、法律结构和发行人治理是这类资产的主要风险源。",
            fit_summary="只适合能接受锁定期和条款尽调的人群。",
            evidence_urls=[HASHKEY_ABOUT_URL, HASHKEY_KYC_URL],
            featured=False,
        ),
        AssetTemplate(
            asset_id="hsk-wbtc-benchmark",
            symbol="WBTC",
            name="HashKey WBTC Benchmark",
            asset_type=AssetType.BENCHMARK,
            description="HashKey Chain 官方列出的 WBTC 合约，用于给 RWA 方案增加一个高波动链上 benchmark。",
            issuer="Wrapped BTC bridge",
            custody="Bridge-backed BTC representation",
            chain_id=chain_id,
            contract_address="0x6119ca49a79f5825c8b345f8d7ac36b272565b14",
            settlement_asset="USDT",
            execution_style="erc20",
            benchmark_apy=0.0,
            expected_return_low=-0.22,
            expected_return_base=0.12,
            expected_return_high=0.35,
            price_volatility=0.62,
            max_drawdown_180d=0.36,
            avg_daily_volume_usd=2_400_000,
            redemption_days=0,
            lockup_days=0,
            management_fee_bps=0,
            entry_fee_bps=0,
            exit_fee_bps=0,
            slippage_bps=12,
            issuer_disclosure_score=0.66,
            custody_disclosure_score=0.64,
            audit_disclosure_score=0.6,
            contract_is_upgradeable=True,
            has_admin_key=True,
            oracle_count=2,
            oracle_sources=["market price feed", "bridge reserves"],
            requires_kyc_level=0,
            minimum_ticket_usd=100,
            tags=["benchmark", "volatile", "non-rwa-anchor"],
            thesis="不是 RWA，但适合作为高波动机会成本基准，帮助用户理解为何 RWA 值得承担额外门槛。",
            fit_summary="仅适合作为比较基准或进取型组合的小比例暴露。",
            evidence_urls=[HASHKEY_TOKEN_CONTRACTS_URL, HASHKEY_NETWORK_INFO_URL],
            featured=False,
        ),
    ]
