import { useMemo } from 'react'
import { useQuery } from '@tanstack/react-query'

import { PageHeader } from '@/components/layout/page-header'
import {
  CalculationCard,
  CalculationEmptyHint,
  EmptyState,
  ErrorState,
  FilterBar,
  LoadingState,
  MetricCard,
  SearchInput,
} from '@/components/product/decision-ui'
import { Button } from '@/components/ui/button'
import { Select } from '@/components/ui/field'
import { useApiAdapter } from '@/lib/api/use-api-adapter'
import { fetchAnalysisCatalog, flattenCalculations } from '@/features/analysis/lib/catalog'
import { calculationTitle } from '@/features/analysis/lib/view-models'
import { useState } from 'react'

export function CalculationsPage() {
  const adapter = useApiAdapter()
  const [search, setSearch] = useState('')
  const [sessionFilter, setSessionFilter] = useState('all')

  const catalogQuery = useQuery({
    queryKey: ['analysis', 'catalog', 'calculations'],
    queryFn: () => fetchAnalysisCatalog(adapter),
  })

  const calculations = useMemo(() => {
    return flattenCalculations(catalogQuery.data ?? { sessions: [], reportsBySession: {} }).filter(
      ({ session, task }) => {
        const matchesSearch =
          !search ||
          `${calculationTitle(task)} ${task.formulaExpression}`
            .toLowerCase()
            .includes(search.toLowerCase())
        const matchesSession = sessionFilter === 'all' || session.id === sessionFilter
        return matchesSearch && matchesSession
      },
    )
  }, [catalogQuery.data, search, sessionFilter])

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="Calculations"
        title="Calculations"
        description="These are deterministic results generated by the calculation module. They remain separate from narrative recommendations so users can inspect formulas, parameters, units, and result notes directly."
      />

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <MetricCard
          title="Breakeven point"
          value={
            calculations.find(({ task }) => task.taskType === 'break-even')?.task.result ??
            'Unavailable'
          }
          detail="Appears when the system can compare two cost paths over time and identify the crossover point."
          tone="brand"
        />
        <MetricCard
          title="Cost crossover"
          value={calculations.find(({ task }) => task.taskType === 'break-even') ? 'Tracked' : 'Not enough data'}
          detail="Useful when a higher-upfront option may become cheaper later."
          tone="success"
        />
        <MetricCard
          title="Budget range"
          value={
            calculations.find(({ task }) => task.taskType === 'budget-band')?.task.result ??
            'Unavailable'
          }
          detail="Low, base, and high outcomes stay explicit when uncertainty is material."
          tone="warning"
        />
        <MetricCard
          title="Sensitivity and drag"
          value={calculations.length ? `${calculations.length} tracked` : 'Missing'}
          detail="The UI shows when there is not enough structured input to calculate something reliably."
          tone="success"
        />
      </div>

      <FilterBar>
        <SearchInput
          value={search}
          onChange={(event) => setSearch(event.target.value)}
          placeholder="Search calculations"
        />
        <Select
          value={sessionFilter}
          onChange={(event) => setSessionFilter(event.target.value)}
        >
          <option value="all">All sessions</option>
          {(catalogQuery.data?.sessions ?? []).map((session) => (
            <option key={session.id} value={session.id}>
              {session.problemStatement}
            </option>
          ))}
        </Select>
      </FilterBar>

      <CalculationEmptyHint />

      {catalogQuery.isLoading ? (
        <LoadingState
          title="Loading calculations"
          description="Preparing formulas, input parameters, and result values."
        />
      ) : catalogQuery.isError ? (
        <ErrorState
          title="Could not load calculations"
          description={(catalogQuery.error as Error).message}
          action={
            <Button variant="secondary" onClick={() => void catalogQuery.refetch()}>
              Retry
            </Button>
          }
        />
      ) : calculations.length ? (
        <div className="space-y-4">
          {calculations.map(({ session, task }) => (
            <CalculationCard
              key={task.id}
              task={task}
              sessionTitle={session.problemStatement}
            />
          ))}
          <div className="grid gap-4 lg:grid-cols-2">
            <div className="panel-card rounded-[24px] p-5">
              <p className="text-sm font-semibold text-text-primary">Supported calculation surfaces</p>
              <p className="mt-2 text-sm leading-6 text-text-secondary">
                Breakeven, budget range, opportunity cost, sensitivity, fee drag, and liquidity-window calculations should read as first-class analytical outputs.
              </p>
            </div>
            <div className="panel-card rounded-[24px] p-5">
              <p className="text-sm font-semibold text-text-primary">Trust rule</p>
              <p className="mt-2 text-sm leading-6 text-text-secondary">
                If the structured input is too weak, the page keeps the empty or warning state visible instead of overstating result readiness.
              </p>
            </div>
          </div>
        </div>
      ) : (
        <EmptyState
          title="No calculations available"
          description="There is not enough structured data yet to show deterministic results for the current filters."
        />
      )}
    </div>
  )
}
